function [R1cut,p1cut] = f1cut(in1,in2,in3)
%F1CUT
%    [R1CUT,P1CUT] = F1CUT(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Mar-2021 11:57:45

q35 = in1(28,:);
q36 = in1(29,:);
q37 = in1(30,:);
q38 = in1(31,:);
q39 = in1(32,:);
t2 = cos(q38);
t3 = cos(q39);
t4 = sin(q38);
t5 = sin(q39);
R1cut = reshape([t3,t4.*t5,-t2.*t5,0.0,t2,t4,t5,-t3.*t4,t2.*t3],[3,3]);
if nargout > 1
    p1cut = [q35;q36;q37];
end
