function out1 = LSHO_Position(in1,in2,in3)
%LSHO_POSITION
%    OUT1 = LSHO_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Mar-2021 11:56:06

R3cut1_1 = in3(19);
R3cut1_2 = in3(22);
R3cut1_3 = in3(25);
R3cut2_1 = in3(20);
R3cut2_2 = in3(23);
R3cut2_3 = in3(26);
R3cut3_1 = in3(21);
R3cut3_2 = in3(24);
R3cut3_3 = in3(27);
p3cut1 = in2(7);
p3cut2 = in2(8);
p3cut3 = in2(9);
q32 = in1(26,:);
q33 = in1(27,:);
t2 = cos(q32);
t3 = cos(q33);
t4 = sin(q32);
t5 = sin(q33);
t6 = R3cut1_1.*t2;
t7 = R3cut2_1.*t2;
t8 = R3cut3_1.*t2;
t9 = R3cut1_2.*t4;
t10 = R3cut2_2.*t4;
t11 = R3cut3_2.*t4;
t12 = t6+t9;
t13 = t7+t10;
t14 = t8+t11;
out1 = [p3cut1+R3cut1_2.*t2.*5.22322e-2-R3cut1_1.*t4.*5.22322e-2-R3cut1_3.*t3.*5.714423077058822e-2-R3cut1_3.*t5.*4.55439e-2+t3.*t12.*4.55439e-2-t5.*t12.*5.714423077058822e-2;p3cut2+R3cut2_2.*t2.*5.22322e-2-R3cut2_1.*t4.*5.22322e-2-R3cut2_3.*t3.*5.714423077058822e-2-R3cut2_3.*t5.*4.55439e-2+t3.*t13.*4.55439e-2-t5.*t13.*5.714423077058822e-2;p3cut3+R3cut3_2.*t2.*5.22322e-2-R3cut3_1.*t4.*5.22322e-2-R3cut3_3.*t3.*5.714423077058822e-2-R3cut3_3.*t5.*4.55439e-2+t3.*t14.*4.55439e-2-t5.*t14.*5.714423077058822e-2];
