function out1 = RSHO_Position(in1,in2,in3)
%RSHO_POSITION
%    OUT1 = RSHO_POSITION(IN1,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.4.
%    26-Mar-2021 11:56:06

R5cut1_1 = in3(37);
R5cut1_2 = in3(40);
R5cut1_3 = in3(43);
R5cut2_1 = in3(38);
R5cut2_2 = in3(41);
R5cut2_3 = in3(44);
R5cut3_1 = in3(39);
R5cut3_2 = in3(42);
R5cut3_3 = in3(45);
p5cut1 = in2(13);
p5cut2 = in2(14);
p5cut3 = in2(15);
q19 = in1(16,:);
q20 = in1(17,:);
t2 = cos(q19);
t3 = cos(q20);
t4 = sin(q19);
t5 = sin(q20);
t6 = R5cut1_1.*t2;
t7 = R5cut2_1.*t2;
t8 = R5cut3_1.*t2;
t9 = R5cut1_2.*t4;
t10 = R5cut2_2.*t4;
t11 = R5cut3_2.*t4;
t12 = t6+t9;
t13 = t7+t10;
t14 = t8+t11;
out1 = [p5cut1+R5cut1_2.*t2.*5.22322e-2-R5cut1_1.*t4.*5.22322e-2+R5cut1_3.*t3.*5.714423077058822e-2-R5cut1_3.*t5.*4.55439e-2+t3.*t12.*4.55439e-2+t5.*t12.*5.714423077058822e-2;p5cut2+R5cut2_2.*t2.*5.22322e-2-R5cut2_1.*t4.*5.22322e-2+R5cut2_3.*t3.*5.714423077058822e-2-R5cut2_3.*t5.*4.55439e-2+t3.*t13.*4.55439e-2+t5.*t13.*5.714423077058822e-2;p5cut3+R5cut3_2.*t2.*5.22322e-2-R5cut3_1.*t4.*5.22322e-2+R5cut3_3.*t3.*5.714423077058822e-2-R5cut3_3.*t5.*4.55439e-2+t3.*t14.*4.55439e-2+t5.*t14.*5.714423077058822e-2];
